/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiktokClipperRouteImport } from './routes/tiktok-clipper'
import { Route as ListSoundRouteImport } from './routes/list-sound'
import { Route as ForEditorsRouteImport } from './routes/for-editors'
import { Route as ForArtistsRouteImport } from './routes/for-artists'
import { Route as ClippingCampaignsRouteImport } from './routes/clipping-campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BountyIdRouteImport } from './routes/bounty.$id'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const TiktokClipperRoute = TiktokClipperRouteImport.update({
  id: '/tiktok-clipper',
  path: '/tiktok-clipper',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSoundRoute = ListSoundRouteImport.update({
  id: '/list-sound',
  path: '/list-sound',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEditorsRoute = ForEditorsRouteImport.update({
  id: '/for-editors',
  path: '/for-editors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForArtistsRoute = ForArtistsRouteImport.update({
  id: '/for-artists',
  path: '/for-artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ClippingCampaignsRoute = ClippingCampaignsRouteImport.update({
  id: '/clipping-campaigns',
  path: '/clipping-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BountyIdRoute = BountyIdRouteImport.update({
  id: '/bounty/$id',
  path: '/bounty/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clipping-campaigns': typeof ClippingCampaignsRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-editors': typeof ForEditorsRoute
  '/list-sound': typeof ListSoundRoute
  '/tiktok-clipper': typeof TiktokClipperRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/bounty/$id': typeof BountyIdRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clipping-campaigns': typeof ClippingCampaignsRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-editors': typeof ForEditorsRoute
  '/list-sound': typeof ListSoundRoute
  '/tiktok-clipper': typeof TiktokClipperRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/bounty/$id': typeof BountyIdRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/clipping-campaigns': typeof ClippingCampaignsRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-editors': typeof ForEditorsRoute
  '/list-sound': typeof ListSoundRoute
  '/tiktok-clipper': typeof TiktokClipperRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/bounty/$id': typeof BountyIdRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clipping-campaigns'
    | '/for-artists'
    | '/for-editors'
    | '/list-sound'
    | '/tiktok-clipper'
    | '/admin'
    | '/dashboard'
    | '/submit'
    | '/bounty/$id'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clipping-campaigns'
    | '/for-artists'
    | '/for-editors'
    | '/list-sound'
    | '/tiktok-clipper'
    | '/admin'
    | '/dashboard'
    | '/submit'
    | '/bounty/$id'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/clipping-campaigns'
    | '/for-artists'
    | '/for-editors'
    | '/list-sound'
    | '/tiktok-clipper'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/submit'
    | '/bounty/$id'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClippingCampaignsRoute: typeof ClippingCampaignsRoute
  ForArtistsRoute: typeof ForArtistsRoute
  ForEditorsRoute: typeof ForEditorsRoute
  ListSoundRoute: typeof ListSoundRoute
  TiktokClipperRoute: typeof TiktokClipperRoute
  BountyIdRoute: typeof BountyIdRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiktok-clipper': {
      id: '/tiktok-clipper'
      path: '/tiktok-clipper'
      fullPath: '/tiktok-clipper'
      preLoaderRoute: typeof TiktokClipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-sound': {
      id: '/list-sound'
      path: '/list-sound'
      fullPath: '/list-sound'
      preLoaderRoute: typeof ListSoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-editors': {
      id: '/for-editors'
      path: '/for-editors'
      fullPath: '/for-editors'
      preLoaderRoute: typeof ForEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-artists': {
      id: '/for-artists'
      path: '/for-artists'
      fullPath: '/for-artists'
      preLoaderRoute: typeof ForArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipping-campaigns': {
      id: '/clipping-campaigns'
      path: '/clipping-campaigns'
      fullPath: '/clipping-campaigns'
      preLoaderRoute: typeof ClippingCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounty/$id': {
      id: '/bounty/$id'
      path: '/bounty/$id'
      fullPath: '/bounty/$id'
      preLoaderRoute: typeof BountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClippingCampaignsRoute: ClippingCampaignsRoute,
  ForArtistsRoute: ForArtistsRoute,
  ForEditorsRoute: ForEditorsRoute,
  ListSoundRoute: ListSoundRoute,
  TiktokClipperRoute: TiktokClipperRoute,
  BountyIdRoute: BountyIdRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
